import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";

import Front from "./front";
import { useState } from "react";

const ExploreSlider = ({ isOpen, onClose }) => {
  return (
    <>
      <div className={` ${isOpen ? "overlay" : ""}`}></div>
      <div className={`slider-container ${isOpen ? "open" : ""}`}>
        <div className={`slider-content ${isOpen ? "open" : ""}`}>
          <p className="text-lg font-semibold mb-4">Select Options:</p>
          {/* Add your slider content and options here */}
          <button
            onClick={onClose}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
};

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isSliderOpen, setSliderOpen] = useState(false);

  const handleButtonClick = () => {
    setSliderOpen(!isSliderOpen);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Priyesh&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="bg-white  dark:bg-gray-900"
        onClick={() => (isSliderOpen ? handleButtonClick() : "")}
      >
        <div className={` min-h-screen ${isSliderOpen ? "divide-x" : ""}`}>
          <div className="flex">
          <div className={` ${isSliderOpen ? "w-1/5" : "w-full"}`}>
            <ExploreSlider
              isOpen={isSliderOpen}
              onClose={() => setSliderOpen(false)}
            />
          </div>

          <div className={`px-0  ${isSliderOpen ? "w-4/5" : "w-full"}`}>
            <nav className="pt-5 pb-5 flex justify-between font-burtons dark:text-white  bg-gradient-to-b from-teal-500 ">
              <h1 onClick={() => handleButtonClick()}>More</h1>

              <ul className="flex items-center justify-between">
                <li className="pl-2">Projects</li>
                <li className="pl-2">Work Experience</li>
              </ul>

              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    className="cursor-pointer text-2xl dark:fill-white"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                </li>
                <li>
                  <a
                    href="/priyesh_resume.pdf"
                    download="Priyesh_Resume.pdf"
                    className="bg-gradient-to-r from-cyan-500 to-text-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            <div className="px-10 md:px-20 lg:px-40">
            <Front />
          </div>
          </div>

        
          </div>
        </div>
      </main>
    </div>
  );
}
