import Head from "next/head";
import { BsFillMoonStarsFill, BsX, BsDownload } from "react-icons/bs";
import Front from "./front";
import { useState } from "react";
import Layout from "./layout";
import Projects from "./projects";



export default function Home() {



  return (
    <div>
    <Head>
    <title>Priyesh&apos;s Portfolio</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <Layout title="Priyesh's Portfolio">
    <Front/>
  
    {/* Rest of your home page content */}
  </Layout>
  </div>
   
  );
}
